jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up PYTHONPATH
        run: export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}

      - name: Run tests
        run: python -m unittest discover -s tests -p "test_*.py"
